docker-timesheets/api/urls.py
from django.urls import path, include
from django.conf import settings
from .views import MonthlyReportCreateView, MonthlyReportListView
from django.conf.urls.static import static
# from users.views import user_logout
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    # -------Visitor urls------------------
    # path('report', report, name="report"),
    path('reports/', MonthlyReportListView.as_view(), name='report-list'),
    path('reports/create/', MonthlyReportCreateView.as_view(), name='report-create'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker-timesheets/timesheet/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import timesheet_list
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_page


urlpatterns = [
    # path('create_timesheet/', create_timesheet, name='create_timesheet'),
    path('', cache_page(60 * 15)(timesheet_list), name="timesheet_list"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docker-timesheets/timesheets_main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('allauth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += i18n_patterns(
    path('', include('general.urls')),
    path('timesheet', include('timesheet.urls')),
    path('reports', include('reports.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
)


# ------------add custom media path for production mode-----------
urlpatterns += re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docker-timesheets/timesheet/models.py
from django.db import models
from users.models import CustomUser


class Activity(models.Model):
    """
    This class creates db tables for the types of actvities
    """
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=6)

    class Meta:
        verbose_name = "Activity"
        verbose_name_plural = "Activities"

    def __str__(self):

        return "{} - {}".format(self.code, self.name)


class FundsSource(models.Model):
    """This class created db tables for the source of funds, which will be selectable from a
    dropdown list when generating a timesheet
    """
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name = "Funds"
        verbose_name_plural = "Funds"

    def __str__(self):
        return self.name


class Timesheet(models.Model):
    """
    This class created db tables for each timesheet, linked to activity model and FundsSource model by ForeinKey relations
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    funds_from = models.CharField(max_length=50)
    date = models.DateField()
    hours_worked = models.DecimalField(max_digits=5, decimal_places=0)
    fundssource = models.ForeignKey(FundsSource, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    description = models.TextField()
    submitted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Timesheet for {self.user.username} - Week of {self.week_start_date}"

docker-timesheets/timesheet/forms.py
from django import forms
from .models import Timesheet
from django.utils.translation import gettext_lazy as _


class TimesheetForm(forms.ModelForm):
    HOURS_CHOICES = [(i, i) for i in range(0, 9)]  # Choices from 0 to 8

    hours_worked = forms.ChoiceField(choices=HOURS_CHOICES, widget=forms.Select(attrs={'class': 'form-select', 'placeholder': _('Select number of hours')}))

    class Meta:
        model = Timesheet
        fields = ['user', 'fundssource', 'date', 'hours_worked', 'activity', 'description']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'id': 'datepicker', 'placeholder': 'Select date'}),
            'fundssource': forms.Select(attrs={'class': 'form-control', 'placeholder': _('Choose funding source')}),
            'activity': forms.Select(attrs={'class': 'form-control', 'placeholder': _('Choose activity')}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Describe activity')}), }

docker-timesheets/timesheet/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime
from .forms import TimesheetForm
from .models import Timesheet, Activity
from django.db.models import Q
import calendar
from django.contrib import messages
from django.utils.translation import gettext_lazy as _


# =============new timesheets view======
# @login_required
# def create_timesheet(request):

#     return render(request, template, context)


# =============list of timesheets per month view======
@login_required
def timesheet_list(request):
    # get current year and month
    current_month = timezone.now().month
    # current_year = timezone.now().year
    # Base queryset
    timesheets = Timesheet.objects.all()
    # Filter by search query
    query = request.GET.get('q', '')
    if query:
        timesheets = timesheets.filter(
            Q(activity__name__icontains=query) | Q(description__icontains=query) | Q(fundssource__name__icontains=query))

    # Filter by month
    month = request.GET.get('month', '')
    if month:
        try:
            month_date = datetime.strptime(month, "%Y-%m")
            timesheets = timesheets.filter(date__year=month_date.year, date__month=month_date.month)
        except ValueError:
            pass  # Invalid month format, ignore the filter

    # Get distinct months for the filter dropdown
    months = [(i, calendar.month_name[i]) for i in range(1, 13)]
    # Get the month and year from GET parameters if available
    try:
        month = int(request.GET.get('month', current_month))
        # year = int(request.GET.get('year', current_year))
    except Exception as e:
        messages.warning(request, e)

    template = 'timesheet/timesheets_list.html'
    # timesheets = Timesheet.objects.filter(date__year=year, date__month=month, user=request.user)
    if request.method == 'POST':
        form = TimesheetForm(request.POST)
        if form.is_valid():
            new_timesheet = form.save(commit=False)
            new_timesheet.user = request.user
            new_timesheet.save()
            messages.success(request, _('Timesheet created successfully!'))
            return redirect('timesheet_list')
        else:
            messages.success(request, _('Please make sure you filled the fields correctly!'))
    else:
        form = TimesheetForm()
    context = {
        'form': form,
        'timesheets': timesheets,
        'months': months
    }
    return render(request, template, context)

docker-timesheets/timesheet/templates/timesheet/timesheets_list.html
{% extends 'general/base.html' %}
{% load static %}
{% load i18n %}
{% load cache %}

{% block title %}{% trans 'Timesheet List' %}{% endblock %}

{% block content %}

    <div class="container mt-4">
        <h1 class="mb-4">{% trans 'Timesheet List' %}</h1>

         <!-- Button to open the modal -->
        <!-- <button id="openModalButton" data-bs-toggle="modal" data-bs-target="#createTimesheetModal" type="button" class="btn btn-primary">
            {% trans 'Add New Timesheet' %}
        </button> -->
         <!-- Button to Open Calendar -->
        <!-- <div class="d-flex justify-content-center mb-4">
            <button type="date" class="btn btn-primary" id="openCalendarBtn">{% trans "Add New Timesheet" %}</button>
        </div> -->
        <!-- Calendar (Date Picker) -->
        <!-- <div id="datepicker-container" class="d-flex justify-content-center mb-4">
            <input type="date" id="datepicker" class="form-control" style="width: 300px;" placeholder="{% trans 'Select date' %}">
        </div> -->
        <form action="#createTimesheetModal">
            <label for="timesheetdate"> {% trans 'Add New Timesheet' %}:</label>
            <!-- <input type="date" id="timesheetdate" name="newtimesheet"> -->
            <input id="openModalButton" data-bs-toggle="modal" data-bs-target="#createTimesheetModal" type="button" class="btn btn-primary" value='Add new timesheet'>
        </form>

            
            
       
        
        <!-- Search and Filter Form -->
        <form method="get" class="mb-4">
            <div class="row">
                <!-- Search Field -->
                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <input type="text" name="q" value="{{ request.GET.q }}" class="form-control" placeholder="{% trans 'Search by activity or date' %}">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">{% trans 'Search' %}</button>
                        </div>
                    </div>
                </div>
                <!-- Month Filter -->
                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <select name="month" class="form-control">
                            <option value="">{% trans 'All Months' %}</option>
                            {% for month in months %}
                                <option value="{{ month.0 }}" {% if request.GET.month == month.0 %}selected{% endif %}>{{ month.1 }}</option>
                            {% endfor %}
                        </select>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">{% trans 'Filter' %}</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% if timesheets %}
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>{% trans 'ID' %}</th>
                        <th>{% trans 'Date' %}</th>
                        <th>{% trans 'Activity' %}</th>
                        <th>{% trans 'Hours' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for timesheet in timesheets %}
                        <tr>
                            <td>{{ timesheet.id }}</td>
                            <td>{{ timesheet.date }}</td>
                            <td>{{ timesheet.activity }}</td>
                            <td>{{ timesheet.hours }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">
                {% trans 'No timesheets found. Please adjust filters' %}.
            </div>
        {% endif %}
    </div>
    <!-- Modal for Creating Timesheet -->
     <!-- Timesheet Modal -->
     <div class="modal fade" id="createTimesheetModal" tabindex="-1" aria-labelledby="createTimesheetModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content custom-modal-height">
                <div class="modal-header">
                    <h5 class="modal-title" id="createTimesheetModalLabel">{% trans "Create New Timesheet" %}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% trans 'Close' %}"></button>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="id_fundssource" class="form-label">{% trans "Funds From" %}</label>
                            {{ form.fundssource }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_date" class="form-label">{% trans "Date" %}</label>
                            {{ form.date }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_date" class="form-label">{% trans "User" %}</label>
                            {{ form.user }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="{{ form.hours_worked.id_for_label }}" class="form-label">{% trans "Hours Worked" %}</label>
                            <div class="input-group">
                                {{ form.hours_worked }}
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="id_activity" class="form-label">{% trans "Activity" %}</label>
                            {{ form.activity }}
                        </div>
                        <div class="mb-3">
                            <label for="id_description" class="form-label">{% trans "Description" %}</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
                        <button type="submit" class="btn btn-primary">{% trans "Save Timesheet" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}